# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 12:48
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubpullrequest',
            options={'verbose_name': 'Pull Request', 'verbose_name_plural': 'Pull Requests'},
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='pull_request_json',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
