# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20160315_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubpullrequest',
            name='diff',
            field=models.TextField(blank=True),
        ),
    ]
