# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 14:39
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_githubpullrequest_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pull_request_json',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
