# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20160329_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubpullrequest',
            name='diff',
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='reviewer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
