# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20160329_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=50)),
                ('sha', models.CharField(blank=True, max_length=50)),
                ('file', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('lines', models.TextField(blank=True)),
            ],
        ),
    ]
