# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20160329_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='pull_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.GitHubPullRequest'),
            preserve_default=False,
        ),
    ]
